---
# prepreqs checks for rocknsm.docket

# Validate hosts exist in stenographer group
- name: docket | check for docket and stenographer hosts
  assert:
    that:
      - "{{ ('docket' in groups) and (groups['docket'] | length) > 0 }}"
      - "{{ ('stenographer' in groups) and (groups['stenographer'] | length) > 0 }}"
    msg: "The [docket] and [stenographer] inventory groups must each have at least one host."

- name: docket | check docket and stenographer hosts for pyopenssl
  yum:
    list=pyOpenSSL
  register: pyopenssl_pkg_status

- name: docket | validate pyopenssl >= 15.0 is installed
  assert:
    that:
      - "{{pyopenssl_pkg_status.results|selectattr('yumstate', 'match', 'installed')|map(attribute='version')| version_compare('15.0.0', '>=' )}}"
    msg: "Docket hosts require PyOpenSSL greater than 15.0 prior to executing this play"

- name: docket | check stenographer host for stenographer
  yum:
    list=stenographer
  register: stenographer_pkg_status

- name: docket | validate stenographer is installed
  assert:
    that:
      - stenographer_pkg_status|json_query('results[?yumstate==`installed`]')|length>0
    msg: Stenographer hosts require the Stenographer package is installed

- name: docket | check docket hosts for {{ docket_web_server }}
  yum:
    list="{{docket_web_server}}"
  register: webserver_pkg_status

- name: docket | validate {{ docket_web_server }} is installed
  assert:
    that:
      - webserver_pkg_status|json_query('results[?yumstate==`installed`]')|length>0
    msg: Docket hosts require {{docket_web_server}} is installed.
