---
# handlers file for rocknsm.docket
- name: cleanup csr on docket host
  file:
    path: "{{docket_x509_key}}.csr"
    state: absent
  when: inventory_hostname in groups['docket']

- name: cleanup csr on sensor hosts
  file:
    path: "{{steno_certs_dir}}/{{hostvars[item].inventory_hostname}}.csr"
    state: absent
  with_items: groups['docket']
  when:
    - inventory_hostname in groups['stenographer']
